var frasi = [
"Quann steva là in Honduras, steva rint a na capanna e nziemm a me ce steva n'american ca parlava, parlava pecché teneva paura. E intant' e sord tuoj nunn arrivavan. 'Na sera gli honduregni me mettetter' nu macete n'man e gridavan': 'Accirel'! Accirel'! Je pregav', pregav' ca corcrun' me venev' a salva', ca tu me veniv' a salva'! Ma nient'... E loro continuavan' a grida' 'Accirel'! O accirimm' nuje a te! E allora l'aggia fatt': aggia abbiat' a taglia' primm' a cap', po 'e bracc, po 'e man'! L'aggia fatt' piezz' piezz'! Mo capisc'?!", 
"Aggia ritt' a Jessica che non mi deve cercare più! Però prima me l'aggia chiavat' e ce so venut' mocc', accussì nun riman' incinta!Oh! Sul' p'o tiemp' ca me stai facenn' perder', je t'avessa spara' mocca! 'E capit?!Sti cazz' e russ': stann' chin' e sord e cattiveria... e se penzan' ca bast' chell p' cumanna'... e se penzan' malament', ce vo' chest'! Tengon' ancora 'nu sacc' e strada 'a fa'. Sono Salvatore Conte! È tutt' appost', Danie'! È appost'! È appost'! Je' o sacc' ca nun è stata cosa toja! T'anna cummannat' e tu n'o sapiv' chi era! Frat't m'ha ritt' tutt'! Sul' na cosa m'interessa a me: chi t'a cummannat' r'accirere a Russo? Genny? E chi allora?",
"'A verità è c'aggia lassat' a Napule 'na banda 'e sciem' ca nun trovan' mang' o cazz' inda a mutanda! Genny è nu pisciazz'! 'A gent' ca te fa guaragna' e sord' nun s'accire, s'accata! A Zecchinett' o vulev'm' bene tutt' quant' assaje! Quando mio figlio era criaturo io 'o purtave sembe a veré 'e scigne, e isse me riceve: «Papà, ma comme è possibile, che degli animali accussì scieme, vogliono fare quello che fanno i cristiani?» 'E scigne, sò belle quando fanno quello che dice il padrone pecché se vogliono comandare da sole diventano pericolose, s'hanne abbattere! ", 
"Brav! E patt sò patt, è 'o vero, Zecchiné? 'Sta vota sit stat fortunat pecché nun simm venut direttament a casa vostra e ce sò fernut miezz tanta cristian ca nun c'azzeccavan nu cazz. Co stu fatt ca vui nir a notte sit tutt ugual, v'a sit cavata bona, ma nun ce pruvà chiù pecché 'a prossima vota ce muvimm c'o iuorn e nuie c'o iuorno nun sbagliamm! Si nun era pe' me tu stiv' ancora a fa' o guagliunciell' appriess' a Ciro! Je t'aggia mannat' là perché dovevi trattare e t'aviva 'mpara'! E me par' ca a coccos' è servut', o no? O mi sbaglio? Stasera te ne vai a piglia' a tua madre e cu fratet' ve ne turnate a' Spagna! Je ve trov' na fatica, 'na cosa tranquilla. Qua lo capisci pure tu, nun putit' resta'! Almen' fin a quann' nun sistem' tutt' cos ch'e Savastan'.",
"Nun ce sta' mammà là dint'!  Nun ce sta nient'! Mammà se n'è ghiuta! Tu ci credi in Dio? Quel Dio che tutto vede e tutto sa? Je ce crer', crer' ca è tutto nu disegno suojo. Quann' tu me purtast' a spara' chillu cristian' p'a prima vota e po' m'e protetto cu' mio padre, Dio sapeva ca l'ira sparat' tu e no je! Quann' Salvatore Conte è turnat', quann' Danielino è muort', iss 'o sapeva. Iss sape tutte cos'! Sapeva pure ca oggi je e te stevema inda 'sta machina, nuje sapimm' chell' ca vulessem' fa, ma solo Dio sap' comm' va' a firni' veramente 'sta storia!",
"Quanno Lelluccio s'è 'nnamurato 'e te, m'ha purtato dint'o ristorante do' faticave tu, pecché vuleve ca te canuscesse. 'O ssaje c'aggio pensato 'a primma vota ca t'aggio vista? 'Chesta è propio 'na cammarera!' Ma me so stata zitta pe' rispetto a isso. Anze aggio ditto accussì: 'Me piace!' Nunn'era 'o vero. Sulo 'na cammarera comm'a te puteva pensa'... 'e ce mettere 'e corna a chillo principe dô figlio mio cu chill'omme 'e mmerda. E mo' comm'a mettimmo nomme, eh? Comme l'accunciammo 'stu fatto, ah Marine'? Comme l'accunciammo ca tutte quante sanno ca figliemo tene 'e ccorna? Hm? Aggio aspetta' ca Lelluccio esce e amm' 'a decidere che n'amm' 'a fa 'e te! ",
"Tutte quante tenimmo 'na ferita, n'umilazione, 'nu muorto 'a chiagnere... ma 'a mano ca c'ha fatte male è sempe 'a stessa: 'e Savastano! Ce sta chi ha perso 'nu frate, coccheduno 'o patre... pe' colpa 'e Gennaro e de' guaglioni suoje. Ma tanto chella è 'na storia passata, è fernuta. Chi ce teneva comm'a schiave mo' sta nascosto dint' a qualche buco do culo! O sta attaccato a qualche machina ca 'o tene in vita... e nun ha da turna' cchiù! Je e Salvatore Conte v'ammo fatte 'na promessa e 'a mantenimmo. Vuje site chille ca contano 'e cchiù 'ncopp'ê chiazze. Oggi chi mette 'e sorde 'ngoppa a 'stu tavolo s'accatta direttamente 'na quota da rrobba ca Salvatore sta facenno arriva'. 'E piazze ca 'e famiglie vostre gestivano a stipendio do' 'e Savastano, sarranno 'e vostre! 'E sorde ca guadagnate v' 'e mettite direttamente dint'a sacca!",
"'E bomboniere po battesimo tuojo. Cinqueciento ne facettemo... 'Nu criaturo 'e curallo dint'e vraccia da Maronna... Accusse vulette mammà toja in omaggio a Maronna do Carmine ca ce facette 'o miracolo. Iettemo pure addo' cierte dutture... dicettero ca essa 'e figlie nunn'e puteva ave'. Patemo me dicette ca er' 'a cambia' mugliera pecché 'nu boss ha da tene' coccheduno ca ce porta 'o cugnome 'nnanze. Je ce dicette ma m'eran' âccidere pecché scegliette 'a mammà toja... e facette bbuono pecché mammà toja me dette a tte, 'nu figlio maschio. E a chillo figlio maschio c'aggio dato l'incarico cchiù importante: accidere a Ciro Di Marzio... e mmece se n'è asciuto cu 'n'accordo fatto 'ncopp'a pella mia!",
"'A vuo' sape' 'a verità, nanne'? 'E femmene nun so' fatte pe' fa' 'e mugliere. È un mestiere difficile assaje, ma c' 'o fanno 'mpara'. E che ti credi, che nun me fosse piaciuto pure a mme, a me fa' 'na vita mia, 'e cazze mieje? Je so' sempe stata 'na femmena libbera, ma a forza 'e carocchie m'hanno fatto cala' 'e 'scelle... e a finale so' stata 'na brava mugliera e 'na buona mamma. Puo' impara' pure tu. Marine', ce sta sultanto 'na manera pe' 'na femmena, si o vero vo' essere libera: nun ha da tene' nisciuno marito o nun l'ha da tenere cchiù",
"Je aggio avuto 'nu regalo. M'hanno arapute ll'uocchie sopra a coccosa ca je tenevo annanze e nun vedevo. Saccio chi è 'o trammite 'e Pietro Savastano. È 'na guagliona, 'a nipote 'e Malammore. Essa nun 'o ssape, ma da chisto mumento tutto chillo ca dice, je 'o sento. At' 'a sta' tranquille, l'aggi' 'a fa' segui' n'ato ppoco. Adoppo a Pietro Savastano 'o facimmo magna' da 'e cane... e cacciato a isso... a nuje 'e Scianel, do figlio sujo ce passa po cazzo!",
"Vint'anne! Sempe cull'uocchie apierte... a fa' attenzione agli amice... 'e nemice... 'e traditure...'E traditure! Vint'anne! E po' aggio passato tutte cose 'mmane a te! 'A barca l'hê tenuta 'mmano tu, Gennari'... e addo c'he purtate a tutte quante? E mo' viene cca a me dicere chillo ca s'ha da fa? Mamma toja m'o diceva sempe: 'Tu 'o vizie troppo assaje. Tutte 'e strunzate ca ce passano pa cape pe' te vanno bene!' Je dicevo: 'Nun te preoccupa'! Puorta pacienza! Chillo nunn'è comm'a mme e comm'a tte, ave bisogno 'e tiempo.'Ma mo' 'o tiempo è fernuto, Genna'! He capite o no? Sì juto troppo annanze!"
]
var titoli = [
"Stasera mi sento un re vuoi essere la mia regina", 
"Vac a fa na pisciat e ce pens", 
"Guagliò sta senz pensier",
"Genny è nu pisciazz'!",
"Saje che si tu? N'anima bbona ch'è caduta dinto a 'na capa storta!",
"Je nun ce torno 'ngalera pe 'na zoccola comm'e tte!",
"E figlie so' lacrime e sango",
"Secondigliano è pure 'a casa mia!",
"Ce repigliammo tutto chillo ch'era 'o nuostro!"
 ]
